package kamerailedovizcevrim.com.kamerledvizevrim;
/**
 * Created by Ibrahim on 26.12.2018.
 */

public class Yardimci {

    public String[] Dovizler={"USD Amerikan Doları",
            "TRY Türk Lirası",
            "EUR Euro",
            "GBP Sterlin",
            "CHF İsviçre Frangı",
            "CNY Çin Yuanı",
            "JPY Japon Yeni",
            "SAR Suudi A. Riyali",
            "NOK Norveç Kronu",
            "DKK Danimarka Kronu",
            "AUD Avustralya Doları",
            "CAD Kanada Doları",
            "SEK İsveç Kronu",
            "KWD Kuveyt Dinarı",
            "IRR İran Riyali",
            "RUB Rus Rublesi",
            "AFN Afganistan Afganisi",
            "AOA Angola Kvanzası",
            "ARS Arjantin Pezosu",
            "ALL Arnavut Leki",
            "AWG Aruba Florini",
            "AZN Azerbaycan Manatı",
            "AED B.A.E. Dirhemi",
            "BSD Bahama Doları",
            "BHD Bahreyn Dinarı",
            "BDT Bangladeş Takası",
            "BBD Barbados Doları",
            "BYR Belarus Rublesi",
            "BZD Belize Doları",
            "BMD Bermuda Doları",
            "BTN Bhutan Ngultrumu",
            "BOB Bolivya Bolivyanosu",
            "BAM Bosna Konvertibl Mark",
            "BWP Botsvana Pulası",
            "BRL Brazilya Reali",
            "BND Brunei Doları",
            "BGN Bulgar Levası",
            "BIF Burundi Frangı",
            "XAF CFA Frangı BEAC",
            "CVE Cape Verde Eskudosu",
            "GIP Cebelitarık Paundu",
            "DZD Cezayir Dinarı",
            "DJF Cibuti Frangı",
            "CZK Çek Korunası",
            "DOP Dominik Pezosu",
            "XCD Doğu Karayip Doları",
            "SVC El Salvador Kolonu",
            "IDR Endonezya Rupisi",
            "ERN Eritre, Nakfa",
            "AMD Ermenistan Dramı",
            "ETB Etiyopya Biri",
            "FKP Falkland Adaları Lirası",
            "MAD Fas Dirhemi",
            "FJD Fiji Doları",
            "PHP Filipinler Pesosu",
            "GMD Gambiya Dalasisi",
            "GHS Gana Cedisi",
            "GNF Gine Frangı",
            "GTQ Guatemala Kuetzalı",
            "GYD Guyana Doları",
            "ZAR Güney Afrika Randı",
            "KRW Güney Kore Wonu",
            "GEL Gürcistan Larisi",
            "HTG Haiti Gurdesi",
            "INR Hindistan Rupisi",
            "ANG Hollanda Antilleri Florini",
            "HNL Honduras Lempirası",
            "HKD Hong Kong Doları",
            "HRK Hırvat Kunası",
            "IQD Irak Dinarı",
            "ILS İsrail Yeni Şekeli",
            "ISK İzlanda Kronu",
            "JMD Jamaika Doları",
            "KHR Kamboçya Rieli",
            "QAR Katar Riyali",
            "KYD Kayman Adaları Doları",
            "KZT Kazakistan Tengesi",
            "KES Kenya Şilini",
            "COP Kolombiya Pezosu",
            "KMF Komor Frangı",
            "CDF Kongo Frangı",
            "CRC Kosta Rika Kolonu",
            "KPW Kuzey Kore Vonu",
            "CUP Küba Pezosu",
            "KGS Kırgızistan Somu",
            "LAK Laos Kipi",
            "LSL Lesotho Lotisi",
            "LVL Letonya Latsı",
            "LRD Liberya Doları",
            "LYD Libya Dinarı",
            "LTL Litvanya Litusu",
            "LBP Lübnan Paundu",
            "HUF Macar Forinti",
            "MGA Madagaskar Doları",
            "MOP Makau Patacası",
            "MKD Makedonya Dinarı",
            "MWK Malavi Kvakası",
            "MVR Maldiv Rufiyası",
            "MYR Malezya Ringiti",
            "MUR Mauritus Rupisi",
            "MXN Meksika Pezosu",
            "MDL Moldova Leyi",
            "MRO Moritanya Ouguiyası",
            "MZN Mozambik Metikali",
            "MNT Moğolistan Tugriki",
            "MMK Myanmar Kyatı",
            "EGP Mısır Lirası",
            "NAD Namibya Doları",
            "NPR Nepal Rupisi",
            "NGN Nijerya Nairası",
            "NIO Nikaragua Kordoba Orosu",
            "UZS Özbekistan Sumu",
            "PAB Panama Balboası",
            "PGK Papua Yeni Gine Kinası",
            "PYG Paraguay Guaranisi",
            "PEN Peru Yeni Solu",
            "PLN Polonya Zlotisi",
            "RON Romen Leyi",
            "RWF Ruanda Frangı",
            "SHP Saint Helena Paundu",
            "WST Samoa Talası",
            "STD Sao Tome ve P. Dobrası",
            "SCR Seyşeller Rupisi",
            "SLL Sierra Leone Leonu",
            "SGD Singapur Doları",
            "SBD Solomon Adaları Doları",
            "SOS Somali Şilini",
            "LKR Sri Lanka Rupisi",
            "SDG Sudan Dinarı",
            "SRD Surinam Doları",
            "SYP Suriye Lirası",
            "SZL Svaziland Lilangenisi",
            "RSD Sırp Dinarı",
            "CLP Şili Pezosu",
            "TJS Tacikistan Somonisi",
            "TZS Tanzanya Şilini",
            "THB Tayland Bahtı",
            "TWD Tayvan Yeni Doları",
            "TOP Tonga Paangası",
            "TTD Trinidad ve Tobago Doları",
            "TND Tunus Dinarı",
            "TMT Türkmenistan Y. Manatı",
            "UGX Uganda Şilini",
            "UAH Ukrayna Hryvniası",
            "OMR Umman Riyali",
            "UYU Uruguay Pezosu",
            "JOD Ürdün Dinarı",
            "VUV Vanuatu Vatusu",
            "VEF Venezuela Bolivarı",
            "VND Vietnam Dongu",
            "YER Yemen Riyali",
            "NZD Yeni Zelanda Doları",
            "ZMW Zambian Kwacha",
            "ZWL Zimbabve Doları"
    };
}



